db:
  image: postgres:9.6.0
  command: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD:secret
    - POSTGRES_USER:postgres
  volumes:
    - db_data:/var/lib/postgresql/data

api:
  build: ./api
  command: mix phoenix.server
  working_dir: /app
  volumes:
    - ./api:/app
  ports:
    - "4000:4000"
  links:
    - db:db.link
  env_file:
    - ./api.env

client:
  image: node:6.9.1
  command: npm start
  volumes:
    - ./client:/app
  ports:
    - "3000:3000"
  working_dir: /app
